# Generated by Django 4.2.1 on 2023-06-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_users_country_users_currency_users_language_and_more'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customerid', models.CharField(max_length=255)),
                ('activate', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('taxid', models.CharField(max_length=100)),
                ('vatnum', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('bill_address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
    ]
