# Generated by Django 4.2.1 on 2023-06-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_stripeproduct_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeproduct',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
