# Generated by Django 4.2.1 on 2023-06-13 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_billinghistory_stripesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='stripecustomer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='membership.stripecustomer'),
        ),
    ]
