# Generated by Django 4.2.1 on 2023-06-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_billinghistory_stripecustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='stripeproduct_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='stripesubscription_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
