# Generated by Django 4.2.1 on 2023-06-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_alter_billinghistory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='stripesubscription_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
