# Generated by Django 4.2.1 on 2023-06-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_billinghistory_stripesubscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stripeproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stripeproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
