# Generated by Django 4.2.3 on 2023-08-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_stripecustomer_created_at_stripecustomer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='bill_address',
            field=models.CharField(max_length=150),
        ),
    ]
