# Generated by Django 4.2.1 on 2023-05-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_category_apidata_datatype'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='apiData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.apidata'),
        ),
        migrations.AlterField(
            model_name='category',
            name='apiData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.apidata'),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='apiData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.apidata'),
        ),
    ]
