# Generated by Django 4.2.1 on 2023-05-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_attribute_apidata_alter_category_apidata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='apiData',
            new_name='apidata',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='apiData',
            new_name='apidata',
        ),
        migrations.RenameField(
            model_name='stockstatus',
            old_name='apiData',
            new_name='apidata',
        ),
    ]
