# Generated by Django 4.2.1 on 2023-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_apidata_attribute_apidata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='apidata',
        ),
        migrations.RemoveField(
            model_name='category',
            name='apidata',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockstatus',
        ),
        migrations.RemoveField(
            model_name='stockstatus',
            name='apidata',
        ),
        migrations.AddField(
            model_name='attribute',
            name='apidata_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='apidata_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='apidata_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stockstatus_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='apidata_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
