# Generated by Django 4.2.1 on 2023-05-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_attribute_apidata_remove_category_apidata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(max_length=250),
        ),
    ]
