# Generated by Django 4.2.1 on 2023-06-20 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_apidata_created_at_apidata_updated_at_and_more'),
        ('product', '0008_attribute_created_at_attribute_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDownloadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('apidata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.apidata')),
            ],
        ),
    ]
