# Generated by Django 4.2.1 on 2023-06-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_apidata_created_at_apidata_updated_at_and_more'),
        ('product', '0009_productdownloadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadProductThreadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('thread_id', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(null=True)),
                ('count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('apidata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.apidata')),
            ],
        ),
    ]
