# Generated by Django 4.2.1 on 2023-06-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_downloadproductthreadstatus_stopped_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadproductthreadstatus',
            name='thread_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
