# Generated by Django 4.2.1 on 2023-07-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_downloadproductthreadstatus_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
