# Generated by Django 4.2.3 on 2023-08-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_optimizeproductthreadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(max_length=100),
        ),
    ]
