# Generated by Django 4.2.1 on 2023-06-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250)),
                ('reference', models.BigIntegerField(default=0)),
                ('activate', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HelpContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('activate', models.BooleanField(default=1)),
                ('helpcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpcenter.helpcategory')),
            ],
        ),
        migrations.CreateModel(
            name='HelpAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('isLike', models.BooleanField()),
                ('helpcontent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpcenter.helpcontent')),
            ],
        ),
    ]
