# Generated by Django 4.2.1 on 2023-06-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_users_avatar'),
        ('helpcenter', '0002_helpcontent_contentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpaudience',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.users'),
        ),
    ]
