# Generated by Django 4.2.1 on 2023-05-27 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('email_verification', models.BooleanField()),
                ('avatar', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.IntegerField()),
                ('gdpr', models.BooleanField()),
                ('opt_url', models.CharField(max_length=250)),
                ('opt_code', models.CharField(max_length=10)),
                ('activate', models.BooleanField()),
                ('role', models.IntegerField(default=1)),
                ('is_first', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('eshopType', models.IntegerField()),
                ('applicationName', models.CharField(default='', max_length=255)),
                ('api_url', models.CharField(max_length=255)),
                ('consumerKey', models.CharField(max_length=255)),
                ('consumerToken', models.CharField(max_length=255)),
                ('activate', models.BooleanField(default=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
    ]
