# Generated by Django 4.2.1 on 2023-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_address_users_mobile_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
    ]
