# Generated by Django 4.2.1 on 2023-05-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_users_is_first'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidata',
            old_name='category',
            new_name='datatype',
        ),
    ]
