# Generated by Django 4.2.1 on 2023-06-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_category_apidata_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
