# Generated by Django 4.2.1 on 2023-06-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='currency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='organization',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='timezone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='zipcode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
