# Generated by Django 4.2.3 on 2023-07-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_apidata_created_at_apidata_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='company',
            field=models.CharField(default='', max_length=50),
        ),
    ]
