# Generated by Django 4.2.3 on 2023-08-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_users_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenaiPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('teaser', models.TextField(default='')),
                ('hint', models.TextField(default='')),
                ('prompt', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
