# Generated by Django 4.2.1 on 2023-06-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadtest', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
